#!/usr/bin/env node
/**
 * run_daily.js — Master Daily Workflow Orchestrator
 * 
 * This is the single entry point for the KiteMCP daily workflow.
 * Usage: npm start   OR   node run_daily.js
 *
 * What it does:
 *   1. Prints the master AI prompt to copy into Antigravity/OpenCode
 *   2. Polls for JSON files generated by each AI agent
 *   3. Auto-runs Node.js scripts (report + export) when data is ready
 *   4. Prints final gate status summary
 */

const { execSync, spawn } = require('child_process');
const fs   = require('fs');
const path = require('path');
const config = require('./lib/config');
const logger = require('./lib/logger');

const TODAY       = new Date().toISOString().split('T')[0];
const REPORTS_DIR = path.join(__dirname, '../reports');
const POLL_MS     = config.gates.pollIntervalMs;
const TIMEOUT_MS  = config.gates.timeoutMs;

// Colours
const G = '\x1b[32m', R = '\x1b[31m', Y = '\x1b[33m', B = '\x1b[34m', X = '\x1b[0m', BOLD = '\x1b[1m';

// ─── Ensure reports directory exists ─────────────────────────────────────────
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  console.log(`${G}Created reports/ directory${X}`);
}

// ─── Print Master AI Prompt ───────────────────────────────────────────────────
console.log(`\n${BOLD}${B}╔═══════════════════════════════════════════════════════════════╗${X}`);
console.log(`${BOLD}${B}║       KiteMCP DAILY WORKFLOW — ${TODAY}              ║${X}`);
console.log(`${BOLD}${B}╚═══════════════════════════════════════════════════════════════╝${X}`);

console.log(`\n${BOLD}${Y}►  STEP 1: Copy this prompt into Antigravity / OpenCode:${X}\n`);
console.log(`${Y}┌─────────────────────────────────────────────────────────────────┐${X}`);
console.log(`${Y}│${X} Run the KiteMCP daily workflow for ${TODAY}.                   ${Y}│${X}`);
console.log(`${Y}│${X} Execute ALL agents in sequence, reading AGENTS.md for rules:   ${Y}│${X}`);
console.log(`${Y}│${X}                                                                 ${Y}│${X}`);
console.log(`${Y}│${X} 1. Run opportunity-scanner (GATE 0)                            ${Y}│${X}`);
console.log(`${Y}│${X} 2. Run commodity-scanner (GATE 0.3, parallel)                  ${Y}│${X}`);
console.log(`${Y}│${X} 3. Run news-scanner (GATE 0.5)                                 ${Y}│${X}`);
console.log(`${Y}│${X} 4. Run portfolio-scanner via Kite MCP (GATE 1)                 ${Y}│${X}`);
console.log(`${Y}│${X} 5. Run intrinsic-value-scanner via Screener.in (GATE 2)        ${Y}│${X}`);
console.log(`${Y}│${X} 6. Run gtt-manager audit (GATE 3)                              ${Y}│${X}`);
console.log(`${Y}│${X}                                                                 ${Y}│${X}`);
console.log(`${Y}│${X} Save all outputs to reports/${TODAY}_*.json                ${Y}│${X}`);
console.log(`${Y}│${X} This script will auto-generate the .md and .xlsx reports       ${Y}│${X}`);
console.log(`${Y}│${X} once the JSON files are ready.                                 ${Y}│${X}`);
console.log(`${Y}└─────────────────────────────────────────────────────────────────┘${X}\n`);

// ─── Define which JSON files we're waiting for ─────────────────────────────
const REQUIRED_JSON = [
  `${TODAY}_portfolio_snapshot.json`,
  `${TODAY}_value_screen.json`,
  `${TODAY}_gtt_audit.json`,
  `${TODAY}_dividend_calendar.json`
];

const OPTIONAL_JSON = [
  `${TODAY}_opportunities.json`,
  `${TODAY}_news_opportunities.json`,
  `${TODAY}_commodity_opportunities.json`,
  `${TODAY}_risk_assessment.json`
];

// Track what's been seen
const seen = new Set();

function checkFile(filename) {
  return fs.existsSync(path.join(REPORTS_DIR, filename));
}

function allRequiredReady() {
  return REQUIRED_JSON.every(f => checkFile(f));
}

function runScript(scriptName) {
  console.log(`\n${B}► Running: node ${scriptName}...${X}`);
  try {
    const output = execSync(`node "${path.join(__dirname, scriptName)}"`, {
      cwd: __dirname,
      encoding: 'utf8',
      timeout: config.gates.scriptTimeoutMs
    });
    console.log(output);
    return true;
  } catch (err) {
    console.error(`${R}✗ ${scriptName} failed:${X}`, err.message);
    return false;
  }
}

// ─── Mode: If all JSON already present, skip waiting ──────────────────────
if (allRequiredReady()) {
  console.log(`${G}✅ Required JSON files already present for ${TODAY}. Generating reports...${X}`);
  const ok1 = runScript('create_master_markdown.js');
  const ok2 = runScript('create_portfolio_export.js');
  const ok3 = runScript('convert_deep_value.js');
  const ok4 = runScript('fetch_commodities.js');
  const ok5 = runScript('create_dividend_calendar.js');
  const ok6 = runScript('create_risk_assessment.js');

  if (ok1 && ok2 && ok3 && ok4 && ok5 && ok6) {
    console.log(`\n${G}${BOLD}✅ Daily workflow complete. Run 'npm run check' before trading.${X}\n`);
  }
  process.exit(ok1 && ok2 && ok3 && ok4 && ok5 && ok6 ? 0 : 1);
}

// ─── Mode: Poll for AI-generated JSON files ──────────────────────────────
console.log(`${B}Waiting for AI agents to generate JSON files...${X}`);
console.log(`${B}(Run the AI prompt above, then come back here)${X}\n`);

let reportsGenerated = false;

const interval = setInterval(() => {
  let newFiles = false;

  // Check optional files
  for (const f of [...OPTIONAL_JSON]) {
    if (!seen.has(f) && checkFile(f)) {
      seen.add(f);
      const gate = f.includes('opportunities.json') ? 'GATE 0' 
                 : f.includes('commodity') ? 'GATE 0.3'
                 : f.includes('news') ? 'GATE 0.5' : '';
      console.log(`${G}✅ ${gate} ${f} received${X}`);
      newFiles = true;
    }
  }

  // Check required files
  for (const f of REQUIRED_JSON) {
    if (!seen.has(f) && checkFile(f)) {
      seen.add(f);
      const gate = f.includes('portfolio') ? 'GATE 1' 
                 : f.includes('value') ? 'GATE 2' 
                 : f.includes('gtt') ? 'GATE 3' : '';
      console.log(`${G}✅ ${gate} ${f} received${X}`);
      newFiles = true;
    }
  }

  // Once required files are ready, generate reports
  if (allRequiredReady() && !reportsGenerated) {
    reportsGenerated = true;
    clearInterval(interval);
    
    console.log(`\n${G}${BOLD}All required gates passed! Generating reports...${X}\n`);
    
    const ok1 = runScript('create_master_markdown.js');
    const ok2 = runScript('create_portfolio_export.js');
    const ok3 = runScript('convert_deep_value.js');
    const ok4 = runScript('fetch_commodities.js');
    const ok5 = runScript('create_dividend_calendar.js');
    const ok6 = runScript('create_risk_assessment.js');

    if (ok1 && ok2 && ok3 && ok4 && ok5 && ok6) {
      console.log(`\n${G}${BOLD}✅ Daily workflow complete!${X}`);
      console.log(`${G}   Reports saved to reports/${TODAY}/${X}`);
      console.log(`${G}   Shortcuts updated in reports/Latest_Report.md and reports/Latest_Portfolio.xlsx${X}`);
      console.log(`\n${Y}► Run 'npm run check' before placing any order.${X}\n`);
    }
    
    process.exit(ok1 && ok2 && ok3 && ok4 && ok5 && ok6 ? 0 : 1);
  }
}, POLL_MS);

// Timeout from config
setTimeout(() => {
  clearInterval(interval);
  const hours = TIMEOUT_MS / (60 * 60 * 1000);
  console.log(`\n${R}⏱ Timeout: AI agents did not complete within ${hours} hours.${X}`);
  console.log(`${Y}   Run 'npm run report' manually after completing AI steps.${X}\n`);
  process.exit(1);
}, TIMEOUT_MS);
